jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,a,d,b,c){return jQuery.easing[jQuery.easing.def](e,a,d,b,c)},easeInQuad:function(e,a,d,b,c){return b*(a/=c)*a+d},easeOutQuad:function(e,a,d,b,c){return-b*(a/=c)*(a-2)+d},easeInOutQuad:function(e,a,d,b,c){return 1>(a/=c/2)?b/2*a*a+d:-b/2*(--a*(a-2)-1)+d},easeInCubic:function(e,a,d,b,c){return b*(a/=c)*a*a+d},easeOutCubic:function(e,a,d,b,c){return b*((a=a/c-1)*a*a+1)+d},easeInOutCubic:function(e,a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a+d:
b/2*((a-=2)*a*a+2)+d},easeInQuart:function(e,a,d,b,c){return b*(a/=c)*a*a*a+d},easeOutQuart:function(e,a,d,b,c){return-b*((a=a/c-1)*a*a*a-1)+d},easeInOutQuart:function(e,a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a*a+d:-b/2*((a-=2)*a*a*a-2)+d},easeInQuint:function(e,a,d,b,c){return b*(a/=c)*a*a*a*a+d},easeOutQuint:function(e,a,d,b,c){return b*((a=a/c-1)*a*a*a*a+1)+d},easeInOutQuint:function(e,a,d,b,c){return 1>(a/=c/2)?b/2*a*a*a*a*a+d:b/2*((a-=2)*a*a*a*a+2)+d},easeInSine:function(e,a,d,b,c){return-b*Math.cos(a/
c*(Math.PI/2))+b+d},easeOutSine:function(e,a,d,b,c){return b*Math.sin(a/c*(Math.PI/2))+d},easeInOutSine:function(e,a,d,b,c){return-b/2*(Math.cos(Math.PI*a/c)-1)+d},easeInExpo:function(e,a,d,b,c){return 0==a?d:b*Math.pow(2,10*(a/c-1))+d},easeOutExpo:function(e,a,d,b,c){return a==c?d+b:b*(-Math.pow(2,-10*a/c)+1)+d},easeInOutExpo:function(e,a,d,b,c){return 0==a?d:a==c?d+b:1>(a/=c/2)?b/2*Math.pow(2,10*(a-1))+d:b/2*(-Math.pow(2,-10*--a)+2)+d},easeInCirc:function(e,a,d,b,c){return-b*(Math.sqrt(1-(a/=c)*
a)-1)+d},easeOutCirc:function(e,a,d,b,c){return b*Math.sqrt(1-(a=a/c-1)*a)+d},easeInOutCirc:function(e,a,d,b,c){return 1>(a/=c/2)?-b/2*(Math.sqrt(1-a*a)-1)+d:b/2*(Math.sqrt(1-(a-=2)*a)+1)+d},easeInElastic:function(e,a,d,b,c){var e=1.70158,f=0,g=b;if(0==a)return d;if(1==(a/=c))return d+b;f||(f=0.3*c);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*(a-=1))*Math.sin(2*(a*c-e)*Math.PI/f))+d},easeOutElastic:function(e,a,d,b,c){var e=1.70158,f=0,g=b;if(0==a)return d;if(1==
(a/=c))return d+b;f||(f=0.3*c);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin(2*(a*c-e)*Math.PI/f)+b+d},easeInOutElastic:function(e,a,d,b,c){var e=1.70158,f=0,g=b;if(0==a)return d;if(2==(a/=c/2))return d+b;f||(f=1.5*0.3*c);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return 1>a?-0.5*g*Math.pow(2,10*(a-=1))*Math.sin(2*(a*c-e)*Math.PI/f)+d:0.5*g*Math.pow(2,-10*(a-=1))*Math.sin(2*(a*c-e)*Math.PI/f)+b+d},easeInBack:function(e,a,d,b,c,f){return void 0==
f&&(f=1.70158),b*(a/=c)*a*((f+1)*a-f)+d},easeOutBack:function(e,a,d,b,c,f){return void 0==f&&(f=1.70158),b*((a=a/c-1)*a*((f+1)*a+f)+1)+d},easeInOutBack:function(e,a,d,b,c,f){return void 0==f&&(f=1.70158),1>(a/=c/2)?b/2*a*a*(((f*=1.525)+1)*a-f)+d:b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+d},easeInBounce:function(e,a,d,b,c){return b-jQuery.easing.easeOutBounce(e,c-a,0,b,c)+d},easeOutBounce:function(e,a,d,b,c){return(a/=c)<1/2.75?7.5625*b*a*a+d:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+d:a<2.5/2.75?b*(7.5625*
(a-=2.25/2.75)*a+0.9375)+d:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+d},easeInOutBounce:function(e,a,d,b,c){return a<c/2?0.5*jQuery.easing.easeInBounce(e,2*a,0,b,c)+d:0.5*jQuery.easing.easeOutBounce(e,2*a-c,0,b,c)+0.5*b+d}});
(function(e,a){e.XY=e.XY||{};XY.dom={getById:function(a){return document.getElementById(a)},get:function(a){return"string"==typeof a?document.getElementById(a):a},createElementIn:function(a,b,c,f){var a=(b=XY.dom.get(b)||document.body).ownerDocument.createElement(a||"div"),e;if("object"==typeof f)for(e in f)"class"==e?a.className=f[e]:"style"==e?a.style.cssText=f[e]:a[e]=f[e];c?b.insertBefore(a,b.firstChild):b.appendChild(a);return a},getStyle:function(a,b){a=XY.dom.get(a);if(!a||9==a.nodeType)return null;
var c=document.defaultView&&document.defaultView.getComputedStyle,f=!c?null:document.defaultView.getComputedStyle(a,"");switch(b){case "float":b=c?"cssFloat":"styleFloat";break;case "opacity":if(c)return parseFloat((f||a.style)[b]);c=100;try{c=a.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(e){try{c=a.filters("alpha").opacity}catch(i){}}return c/100;case "backgroundPositionX":if(c)return(f||a.style).backgroundPosition.split(" ")[0];break;case "backgroundPositionY":if(c)return(f||a.style).backgroundPosition.split(" ")[1]}return c?
(f||a.style)[b]:a.currentStyle[b]||a.style[b]},setStyle:function(a,b,c){if(!(a=XY.dom.get(a))||1!=a.nodeType)return!1;var f,e=!0,i=(f=document.defaultView)&&f.getComputedStyle,j=/z-?index|font-?weight|opacity|zoom|line-?height/i;"string"==typeof b&&(f=b,b={},b[f]=c);for(var h in b){c=b[h];if("float"==h)h=i?"cssFloat":"styleFloat";else if("opacity"==h)i||(h="filter",c=1<=c?"":"alpha(opacity="+Math.round(100*c)+")");else if("backgroundPositionX"==h||"backgroundPositionY"==h)if(f="X"==h.slice(-1)?"Y":
"X",i){var k=XY.dom.getStyle(a,"backgroundPosition"+f);h="backgroundPosition";"number"==typeof c&&(c+="px");c="Y"==f?c+" "+(k||"top"):(k||"left")+" "+c}"undefined"!=typeof a.style[h]?(a.style[h]=c+("number"===typeof c&&!j.test(h)?"px":""),e=e&&!0):e=e&&!1}return e},getScrollTop:function(a){a=a||document;return Math.max(a.documentElement.scrollTop,a.body.scrollTop)},getClientHeight:function(a){a=a||document;return"CSS1Compat"==a.compatMode?a.documentElement.clientHeight:a.body.clientHeight}};XY.string=
{RegExps:{trim:/^\s+|\s+$/g,ltrim:/^\s+/,rtrim:/\s+$/,nl2br:/\n/g,s2nb:/[\x20]{2}/g,URIencode:/[\x09\x0A\x0D\x20\x21-\x29\x2B\x2C\x2F\x3A-\x3F\x5B-\x5E\x60\x7B-\x7E]/g,escHTML:{re_amp:/&/g,re_lt:/</g,re_gt:/>/g,re_apos:/\x27/g,re_quot:/\x22/g},escString:{bsls:/\\/g,sls:/\//g,nl:/\n/g,rt:/\r/g,tab:/\t/g},restXHTML:{re_amp:/&amp;/g,re_lt:/&lt;/g,re_gt:/&gt;/g,re_apos:/&(?:apos|#0?39);/g,re_quot:/&quot;/g},write:/\{(\d{1,2})(?:\:([xodQqb]))?\}/g,isURL:/^(?:ht|f)tp(?:s)?\:\/\/(?:[\w\-\.]+)\.\w+/i,cut:/[\x00-\xFF]/,
getRealLen:{r0:/[^\x00-\xFF]/g,r1:/[\x00-\xFF]/g},format:/\{([\d\w\.]+)\}/g},commonReplace:function(a,b,c){return a.replace(b,c)},format:function(d){var b=Array.prototype.slice.call(arguments),c,d=String(b.shift());1==b.length&&"object"==typeof b[0]&&(b=b[0]);XY.string.RegExps.format.lastIndex=0;return d.replace(XY.string.RegExps.format,function(d,e){c=XY.object.route(b,e);return c===a?d:c})}};XY.object={routeRE:/([\d\w_]+)/g,route:function(d,b){var d=d||{},b=String(b),c=XY.object.routeRE,e;for(c.lastIndex=
0;null!==(e=c.exec(b))&&!(d=d[e[0]],d===a||null===d););return d}};(XY.userAgent={}).ie=9-(-1<navigator.userAgent.indexOf("Trident/5.0")?0:1)-(e.XDomainRequest?0:1)-(e.XMLHttpRequest?0:1);"undefined"==typeof XY.msgbox&&(XY.msgbox={});XY.msgbox._timer=null;XY.msgbox.loadingAnimationPath=XY.msgbox.loadingAnimationPath||"../js/msgbox/loading.gif";XY.msgbox.show=function(a,b,c,e){"number"==typeof e&&(e={topPosition:e});var e=e||{},g=XY.msgbox,i='<img src="'+(e.customIcon||g.loadingAnimationPath)+'" alt="" />',
j;g._loadCss&&g._loadCss(e.cssPath);j=XY.dom.get("q_Msgbox")||XY.dom.createElementIn("div",document.body,!1,{className:"xy_msgbox_layer_wrap"});j.id="q_Msgbox";j.style.display="";j.innerHTML=XY.string.format('<span class="xy_msgbox_layer" style="display:none;z-index:10000;" id="mode_tips_v2"><span class="gtl_ico_{type}"></span>{loadIcon}{msgHtml}<span class="gtl_end"></span></span>',{type:[0,0,0,0,"succ","fail","clear"][b]||"hits",msgHtml:a||"",loadIcon:6==b?i:""});g._setPosition(j,c,e.topPosition)};
XY.msgbox._setPosition=function(a,b,c){var b=b||5E3,e=XY.msgbox,g=XY.dom.getScrollTop(),i=XY.dom.getClientHeight(),i=Math.floor(i/2)-40;XY.dom.setStyle(a,"top",("BackCompat"==document.compatMode||7>XY.userAgent.ie?g:0)+("number"==typeof c?c:i)+"px");clearTimeout(e._timer);a.firstChild.style.display="";b&&(e._timer=setTimeout(e.hide,b))};XY.msgbox.hide=function(a){var b=XY.msgbox;a?(clearTimeout(b._timer),b._timer=setTimeout(b._hide,a)):b._hide()};XY.msgbox._hide=function(){var a=XY.dom.get("q_Msgbox");
clearTimeout(XY.msgbox._timer);a&&XY.dom.setStyle(a,"display","none")}})(window);
$(function(){var e=[],a=-1;$("#littleBoxes > div").each(function(){var a=$(this),a={index:a.index(),top:a.css("top"),left:a.css("left")};e.push(a)});$("#littleBoxes a.head").bind("click",function(d){var b=$(this).parent();b.css("z-index","1");a==b.index()?(b.stop().animate({top:e[b.index()].top,left:e[b.index()].left,width:"90px",height:"90px"},800,"easeOutBack").find(".boxcontent").fadeOut(),$("#littleBoxes > div").not(b).each(function(){var a=$(this),b=e[a.index()].top,d=e[a.index()].left;a.stop().show().animate({top:b,
left:d,opacity:1},800)}),a=-1):($("#littleBoxes > div").not(b).each(function(){$(this).stop().animate({top:Math.floor(601*Math.random())-150+"px",left:Math.floor(601*Math.random())-150+"px",opacity:0},800,function(){$(this).hide()})}),b.stop().animate({top:"0px",left:"0px",width:"379px",height:"379px"},800,"easeOutBack",function(){a=b.index();$(this).find(".boxcontent").fadeIn()}));d.preventDefault()})});
$(function(){var e=window.XY||{};$("#msgBtn").on("click",function(a){var d=$(a.currentTarget),a=$("#mailMe").serializeArray(),b={};d.find("img").show();$.each(a,function(a,d){b[d.name]=d.value});console.log(b);$.ajax({type:"POST",url:"mail/simpleEmail.php",data:a,success:function(a){a=eval("("+a+")");d.find("img").hide();$("#mailMe").find('input[type="text"], textarea').val("");e.msgbox.show(a.username+"，来信已收到，我会尽快回复！",4,3E3)}})})});
